build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:trixie
labels:
  org.opencontainers.image.title: Reachy Mini
  org.opencontainers.image.source: https://github.com/atterdal/ha-reachy-mini
